objects/Debt__c/Debt__c.object-meta.xml
<CustomObject>
    <label>Debt</label>
    <nameField>
        <label>Debt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Debt__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Debt__c/fields/MinPaymentPercentage__c.field-meta.xml
<CustomField>
    <fullName>MinPaymentPercentage__c</fullName>
    <label>Min Payment Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

classes/DebtDatatableController.cls
public with sharing class DebtDatatableController {

    @AuraEnabled(cacheable=true)
    public static List<Debt__c> getDebtList() {
        return [
            SELECT 
                Id, FirstName__c , LastName__c, CreditorName__c, MinPaymentPercentage__c, Balance__c
            FROM Debt__c
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled
    public static void deleteDebts(Id[] debtIds){
        delete [
            SELECT 
                Id  
            FROM Debt__c 
            WHERE Id IN: debtIds
        ];
    }
}